### ISSUE TITLE
DCI decoding and RNTI discovery Issues

### ISSUE THREAD

**Issue by olasierra** [PrincetonUniversity/NR-Scope#18]
Hi, first of all thanks a lot for sharing this incredible tool. 

I've been testing it in controlled a lab environment.

**Testbed Setup:**
The gNB/Core setup uses a 5G SA open source (srsRAN Project + Open5GS [link](https://docs.srsran.com/projects/project/en/latest/tutorials/source/cotsUE/source/index.html)). I have connected COTS device (Samsung Galaxy S23 and sysmocom programable SIM card), achieving a stable control plane (CP) and user plane (UP) connection.
![image](https://github.com/user-attachments/assets/8e0c41f1-7ddb-445a-be9b-3b52724d5ae6)
![image](https://github.com/user-attachments/assets/cc431930-340a-4c03-8a1a-635357e0c0fc)

In this setup, I deployed the NR-Scope sniffer and managed to successfully find the cell and decode System Information 1 DCIs:
![image](https://github.com/user-attachments/assets/4ec34a1f-af67-45d9-a50b-39f806ee9cb0)
However, I was unable to decode any further DCIs associated with the user RNTI (neither RACH nor PDCCH).

**Questions:**
- Do you know why it might fail to decode further DCIs? Or why the tool does not seem to attempt decoding user DCIs (C-RNTI) beyond the System Information DCIs?
- I would also appreciate if you could you provide more insight into the algorithm used to find user RNTIs. From my initial review of the code, it appears to brute-force through the RNTI index.

Thanks in advance!

**Comment by WanHaoRan** [comment]
Hi, thanks for trying our tool. At this stage (after decoding the SIB 1), the code tries to decode the RACH by first searching for the DCI used for MSG 4 and then try to decode the content of MSG 4 and RRCSetup. To make NR-Scope aware your phone's RACH, you may need to toggle airplane mode on your phone to perform RACH again. Since the RACH (MSG 1- 4) only happens once for each phone, and if NR-Scope misses the MSG 4, it misses the phone.

To make it detect your phone, you may:

- Toggle airplane mode on your phone and see if NR-Scope can decode the MSG 4.
- Re-run the code and connect the phone into the network after NR-Scope decodes SIB 1.

Also, could you check the commandline output (if you saved it) and see if the SIB 1's content is correctly decoded?

For your questions:

- The reason it fail to decode further DCIs could be:
  1) The situation I listed above -- the phone is already connected thus no RACH message is exchanged and detected.  
  2) The SIB 1 is not corrected decoded, even NR-Scope finds the DCI for SIBs, it may fail to decode the content of the SIB 1. Could you check the commandline output to find out if the SIB 1's content is correctly decoded.
  3) Lost of synchronization. I see your USRP has an internal GPS, which is good, does the srsRAN's USRP also has a reference signal or clock for synchronization? 
- Sure, after decoding the SIB 1, the code will try to find RACH MSG 4 through the information provided by SIB 1. When a UE connects to the RAN, the base station and UE will exchange 4 messages (MSG 1 and 3 are uplink; MSG 2 and 4 are downlink), where NR-Scope will try to decode the MSG 4. It's not brute-force, as at this stage, the DCI payload is not scrambled with TC-RNTI, so the code will perform one XOR to acquire the TC-RNTI, which will be used as C-RNTI later. But after RACH, the DCI payload will be scrambled with C-RNTI, if we don't have the C-RNTI beforehand, we will have to do the brute-force C-RNTI searching (65536 possibilities). This is why we try to decode the RACH and acquire the C-RNTI beforehand.

**Comment by WanHaoRan** [comment]
Oh, another thing about the srsRAN base station is that you may need to change the default MCS table to 64 qam by commenting line 1047 (`pdsch_hl_cfg.mcs_table = srsran_mcs_table_256qam;`) and 1120 (`pusch_hl_cfg.mcs_table = srsran_mcs_table_256qam;`) in `nrscope/src/libs/dci_decoder.cc`, this is because the srsRAN uses 64 qam by default and all the other base stations use 256qam. The MCS table information is delivered through encrypted RRC Reconfiguration, which we can't decode over the air.

**Comment by olasierra** [comment]
Hi, thanks for reaching out. With your explaination it is more clear now.
So first I the two lines as suggested within nrscope/src/libs/dci_decoder.cc.
Then, reviewed that first NR-Scope was decoding the SIB1 DCI (PDCCH). Looking and comparing the parameters from NR-Scope and te ones generated in srsRAN I think that the SI-DCI has been properly decoded...

However, the SIB1 message (PDSCH) could not be extracted. From the 8 attempts in none of them SIB1 could be extracted... The error that I have encountered is is the following:

Simplified Error output, 3 out of 8:
```
...
PDSCH-DMRS: RSRP=+17.35dB EPRE=+17.56dB CFO=-1107Hz Sync=-0.579us
SIBDecoder -- Error decoding PDSCH (CRC)
...
PDSCH-DMRS: RSRP=+17.34dB EPRE=+17.54dB CFO=-1113Hz Sync=-0.873us
SIBDecoder -- Error decoding PDSCH (CRC)
...
PDSCH-DMRS: RSRP=+17.22dB EPRE=+17.48dB CFO=-1092Hz Sync=-1.469us
SIBDecoder -- Error decoding PDSCH (CRC)
...
```
1 out of 8 attempts, Commandline output:
```
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=0, EPRE=+17.50, RSRP=+17.14, corr=0.920; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=1, al=0, EPRE=+21.67, RSRP=+21.10, corr=0.876; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=2, al=0, EPRE=+18.00, RSRP=+17.41, corr=0.872; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=3, al=0, EPRE=+22.51, RSRP=+22.12, corr=0.913; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=0, EPRE=+5.76, RSRP=-2.24, corr=0.159; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=5, al=0, EPRE=-4.42, RSRP=-11.43, corr=0.199; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=6, al=0, EPRE=-5.67, RSRP=-11.51, corr=0.260; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=7, al=0, EPRE=-5.18, RSRP=-9.75, corr=0.349; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=1, EPRE=+20.07, RSRP=+16.52, corr=0.441; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=2, al=1, EPRE=+20.81, RSRP=+18.13, corr=0.539; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=1, EPRE=+3.15, RSRP=-7.30, corr=0.090; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=6, al=1, EPRE=-5.41, RSRP=-14.28, corr=0.130; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=2, EPRE=+20.46, RSRP=+19.07, corr=0.726; nof_bits=37; crc=OK;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=2, EPRE=+0.70, RSRP=-11.73, corr=0.057; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=3, EPRE=+17.49, RSRP=+12.67, corr=0.329; nof_bits=37; crc=KO;
SIBDecoder -- Found DCI: si-rnti=0xffff dci=1_0 ss=common0 L=2 cce=0 f_alloc=0xd8 t_alloc=0x0 vrb_to_prb_map=0 mcs=5 rv=0 sii=0 coreset0_bw=24 reserved=0x0 
PDSCH_cfg:
  DMRS:
    type=1
    add_pos=2
    len=single
    typeA_pos=2
    rvd_pattern: begin=0 end=275 stride=1 sc=111111111111 symb=00100001000100 
  Grant:
    rnti=0xffff
    rnti_type=SI-RNTI
    k=0
    mapping=A
    t_alloc=2:12
    f_alloc=0:10
    nof_dmrs_cdm_grps=2
    beta_dmrs=1.412538
    nof_layers=1
    n_scid=0
    tb_scaling_field=0
    CW0:
      mod=QPSK
      nof_layers=1
      mcs=5
      tbs=808
      R=0.370
      rv=0
      ndi=0
      nof_re=1080
      nof_bits=2160
  SCH:
    mcs_table=64qam
    xoverhead=0
producer time_spend: 951(us)
current_produce_at: 863
current_produce_ptr: 0x7d2ff79b3100
current_consume_at: 862
pre_resampling_sf_sz: 23040
decode slot: 2; current_consume_ptr: 0x7d2ff7986100
pre_resampling_sf_sz: 23040
decode slot: 3; current_consume_ptr: 0x7d2ff799c900
consumer time_spend: 51(us)
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=0, EPRE=-21.40, RSRP=-31.56, corr=0.096; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=1, al=0, EPRE=-20.44, RSRP=-24.39, corr=0.403; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=2, al=0, EPRE=-22.79, RSRP=-30.07, corr=0.187; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=3, al=0, EPRE=-23.26, RSRP=-30.18, corr=0.203; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=0, EPRE=-21.99, RSRP=-33.81, corr=0.066; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=5, al=0, EPRE=-21.44, RSRP=-30.77, corr=0.117; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=6, al=0, EPRE=-21.47, RSRP=-28.94, corr=0.179; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=7, al=0, EPRE=-21.52, RSRP=-27.57, corr=0.249; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=1, EPRE=-20.90, RSRP=-33.25, corr=0.058; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=2, al=1, EPRE=-23.02, RSRP=-29.90, corr=0.205; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=1, EPRE=-21.71, RSRP=-41.86, corr=0.010; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=6, al=1, EPRE=-21.50, RSRP=-43.49, corr=0.006; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=2, EPRE=-21.83, RSRP=-35.76, corr=0.040; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=2, EPRE=-21.60, RSRP=-37.83, corr=0.024; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=3, EPRE=-21.71, RSRP=-41.60, corr=0.010; nof_bits=37; crc=KO;
SIBDecoder -- No DCI found :'(
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=0, EPRE=-18.23, RSRP=-28.64, corr=0.091; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=1, al=0, EPRE=-19.76, RSRP=-28.70, corr=0.128; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=2, al=0, EPRE=-21.17, RSRP=-31.24, corr=0.098; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=3, al=0, EPRE=-21.30, RSRP=-29.04, corr=0.168; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=0, EPRE=-20.15, RSRP=-30.73, corr=0.088; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=5, al=0, EPRE=-18.93, RSRP=-28.46, corr=0.111; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=6, al=0, EPRE=-22.30, RSRP=-26.65, corr=0.367; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=7, al=0, EPRE=-18.93, RSRP=-27.92, corr=0.126; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=1, EPRE=-18.92, RSRP=-32.10, corr=0.048; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=2, al=1, EPRE=-21.24, RSRP=-37.67, corr=0.023; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=1, EPRE=-19.50, RSRP=-33.59, corr=0.039; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=6, al=1, EPRE=-20.30, RSRP=-26.10, corr=0.263; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=2, EPRE=-19.93, RSRP=-35.60, corr=0.027; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=4, al=2, EPRE=-19.88, RSRP=-33.22, corr=0.046; nof_bits=37; crc=KO;
PDCCH: si-rnti=0xffff, crst_id=0, ss_type=common0, ncce=0, al=3, EPRE=-19.90, RSRP=-34.27, corr=0.037; nof_bits=37; crc=KO;
SIBDecoder -- No DCI found :'(
symbol_sz in dmrs_sch: 288
slot_idx in srsran_dmrs_sch_seed: 1

slot_idx in srsran_dmrs_sch_seed: 1

slot_idx in srsran_dmrs_sch_seed: 1

srsran_vec_estimate_freq: -0.106184
srsran_vec_estimate_freq: -0.106361
srsran_vec_estimate_freq: -0.106250
PDSCH-DMRS: RSRP=+17.07dB EPRE=+17.38dB CFO=-1102Hz Sync=-1.771us
SIBDecoder -- Error decoding PDSCH (CRC)
producer time_spend: 1049(us)
current_produce_at: 864
current_produce_ptr: 0x7d2ff79e0100
current_consume_at: 863
pre_resampling_sf_sz: 23040
decode slot: 4; current_consume_ptr: 0x7d2ff79b3100
pre_resampling_sf_sz: 23040
decode slot: 5; current_consume_ptr: 0x7d2ff79c9900
consumer time_spend: 46(us)
```
Any help will be much appreciated! 

## Additional information:
#### DCI Info Comparison: NR-Scope vs. srsRAN
| **NR-Scope PDCCH SIB1 DCI:**          | **srsRAN PDCCH SIB1 DCI:**          | **NR-Scope PDSCH SIB1 Config:**       | **srsRAN PDSCH SIB1 Config:**         |
|---------------------------------------|-------------------------------------|---------------------------------------|---------------------------------------|
| SIBDecoder -- Found DCI:              | **DCI Configuration:**             | **PDSCH.cfg:**                        | **PDSCH Information:**               |
| si-rnti=0xffff                        | N_rb_dl_bwp: 24                    | DMRS:                                 | RNTI: 65535                          |
| dci=1_0                               | Frequency Resource (RIV): 216      | - type=1                              | **BWP Configuration:**               |
| ss=common0                            | VRB to PRB Mapping: 0              | - add_pos=2                           | - Cyclic Prefix (CP): 0              |
| L=2                                   | Tone Resource: 0                   | - len=single                          | - Component RBs (CRBs):              |
| cce=0                                 | Modulation and Coding Scheme (MCS): 5 | - typeA_pos=2                         |   - Start: 0                         |
| f_alloc=0xd8 =216                     | Redundancy Version: 0              | - rvd_pattern: begin=0 end=275        |   - Length: 51                       |
| t_alloc=0x0                           | System Information Indicator: 0    | - sc=11111111111 symb=00010001001000  | - Subcarrier Spacing (SCS): 30 kHz   |
| vrb_to_prb_map=0                      |                                     | Grant:                                | **CORESET Configuration:**           |
| mcs=5                                 |                                     | rnti=0xffff                           | - Start CRB: 0                       |
| rv=0                                  |                                     | mti_type=SI-RNTI                      | - Duration: 2 symbols                |
| sii=0                                 |                                     | k=0                                   | - Number of CCEs: 8                  |
| coreset0_bw=24                        |                                     | mapping=A                             | - Interleaved Mapping: Yes           |
| reserved=0x0                          |                                     | t_alloc=2:12                          | - PDCCH DMRS Scrambling ID: Not Configured |
|                                       |                                     | f_alloc=0x10                          | **OFDM Symbols:**                    |
|                                       |                                     | nof_dmrs_cdm_grps=2                   | - Start: 2                           |
|                                       |                                     | nof_layers=1                          | - Length: 12                         |
|                                       |                                     | t_scaling_field=0                     | **Codeword Configuration:**          |
|                                       |                                     | **CWO:**                              | - RV Index: 0                        |
|                                       |                                     | mod=QPSK                              | - MCS Index: 5                       |
|                                       |                                     | nof_layers=1                          | - MCS Table: QAM64                   |
|                                       |                                     | mcs=5                                 | - TBS (Bytes): 101                   |
|                                       |                                     | tbs=808                               | **DMRS Configuration:**              |
|                                       |                                     | r=0.30                                | - Config Type: 1                     |
|                                       |                                     | rv=0                                  | - DMRS Ports: 1                      |
|                                       |                                     | ndl=0                                 | - DMRS Scrambling ID: Not Configured |
|                                       |                                     | nof_bits=1080                         |                                       |
|                                       |                                     | xoverhead=0                           |                                       |


####  SIB1 Message Generated at srsRAN gNB:
```
2024-12-09T09:53:18.562779 [DU-MNG  ] [I] SIB1 cell=0: {
  "cellSelectionInfo": {
    "q-RxLevMin": -70,
    "q-QualMin": -20
  },
  "cellAccessRelatedInfo": {
    "plmn-IdentityInfoList": [
      {
        "plmn-IdentityList": [
          {
            "mcc": [
              0,
              0,
              1
            ],
            "mnc": [
              0,
              1
            ]
          }
        ],
        "trackingAreaCode": "000000000000000000000111",
        "cellIdentity": "000000000000011001101100000000000000",
        "cellReservedForOperatorUse": "notReserved"
      }
    ]
  },
  "connEstFailureControl": {
    "connEstFailCount": "n1",
    "connEstFailOffsetValidity": "s30",
    "connEstFailOffset": 1
  },
  "servingCellConfigCommon": {
    "downlinkConfigCommon": {
      "frequencyInfoDL": {
        "frequencyBandList": [
          {
            "freqBandIndicatorNR": 78
          }
        ],
        "offsetToPointA": 0,
        "scs-SpecificCarrierList": [
          {
            "offsetToCarrier": 0,
            "subcarrierSpacing": "kHz30",
            "carrierBandwidth": 51,
            "txDirectCurrentLocation": 306
          }
        ]
      },
      "initialDownlinkBWP": {
        "genericParameters": {
          "locationAndBandwidth": 13750,
          "subcarrierSpacing": "kHz30"
        },
        "pdcch-ConfigCommon": {
          {
            "commonSearchSpaceList": [
              {
                "searchSpaceId": 1,
                "controlResourceSetId": 0,
                "monitoringSlotPeriodicityAndOffset": {
                },
                "monitoringSymbolsWithinSlot": "10000000000000",
                "nrofCandidates": {
                  "aggregationLevel1": "n0",
                  "aggregationLevel2": "n0",
                  "aggregationLevel4": "n1",
                  "aggregationLevel8": "n0",
                  "aggregationLevel16": "n0"
                },
                "searchSpaceType": {
                  "common": {
                    "dci-Format0-0-AndFormat1-0": {
                    }
                  }
                }
              }
            ],
            "searchSpaceSIB1": 0,
            "pagingSearchSpace": 1,
            "ra-SearchSpace": 1
          }
        },
        "pdsch-ConfigCommon": {
          {
            "pdsch-TimeDomainAllocationList": [
              {
                "mappingType": "typeA",
                "startSymbolAndLength": 53
              },
              {
                "mappingType": "typeA",
                "startSymbolAndLength": 72
              }
            ]
          }
        }
      },
      "bcch-Config": {
        "modificationPeriodCoeff": "n4"
      },
      "pcch-Config": {
        "defaultPagingCycle": "rf128",
        "nAndPagingFrameOffset": {
        },
        "ns": "one"
      }
    },
    "uplinkConfigCommon": {
      "frequencyInfoUL": {
        "frequencyBandList": [
          {
            "freqBandIndicatorNR": 78
          }
        ],
        "absoluteFrequencyPointA": 626728,
        "scs-SpecificCarrierList": [
          {
            "offsetToCarrier": 0,
            "subcarrierSpacing": "kHz30",
            "carrierBandwidth": 51
          }
        ]
      },
      "initialUplinkBWP": {
        "genericParameters": {
          "locationAndBandwidth": 13750,
          "subcarrierSpacing": "kHz30"
        },
        "rach-ConfigCommon": {
          {
            "rach-ConfigGeneric": {
              "prach-ConfigurationIndex": 159,
              "msg1-FDM": "one",
              "msg1-FrequencyStart": 6,
              "zeroCorrelationZoneConfig": 0,
              "preambleReceivedTargetPower": -100,
              "preambleTransMax": "n7",
              "powerRampingStep": "dB4",
              "ra-ResponseWindow": "sl20"
            },
            "ssb-perRACH-OccasionAndCB-PreamblesPerSSB": {
              "one": "n64"
            },
            "ra-ContentionResolutionTimer": "sf64",
            "prach-RootSequenceIndex": {
              "l139": 1
            },
            "msg1-SubcarrierSpacing": "kHz30",
            "restrictedSetConfig": "unrestrictedSet"
          }
        },
        "pusch-ConfigCommon": {
          {
            "pusch-TimeDomainAllocationList": [
              {
                "k2": 4,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 5,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 6,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 7,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              },
              {
                "k2": 11,
                "mappingType": "typeA",
                "startSymbolAndLength": 27
              }
            ],
            "msg3-DeltaPreamble": 6,
            "p0-NominalWithGrant": -76
          }
        },
        "pucch-ConfigCommon": {
          {
            "pucch-ResourceCommon": 11,
            "pucch-GroupHopping": "neither",
            "p0-nominal": -90
          }
        }
      },
      "timeAlignmentTimerCommon": "infinity"
    },
    "n-TimingAdvanceOffset": "n25600",
    "ssb-PositionsInBurst": {
      "inOneGroup": "10000000"
    },
    "ssb-PeriodicityServingCell": "ms10",
    "tdd-UL-DL-ConfigurationCommon": {
      "referenceSubcarrierSpacing": "kHz30",
      "pattern1": {
        "dl-UL-TransmissionPeriodicity": "ms5",
        "nrofDownlinkSlots": 6,
        "nrofDownlinkSymbols": 8,
        "nrofUplinkSlots": 3,
        "nrofUplinkSymbols": 0
      }
    },
    "ss-PBCH-BlockPower": -16
  },
  "ue-TimersAndConstants": {
    "t300": "ms1000",
    "t301": "ms1000",
    "t310": "ms1000",
    "n310": "n1",
    "t311": "ms3000",
    "n311": "n1",
    "t319": "ms1000"
  }
}
```

**Comment by WanHaoRan** [comment]
Hi, thanks for the update. Yes, the DCI for SIB 1 is correctly decoded, but the PDSCH decoding fails. Also, the signal power of both PDCCH and PDSCH looks good, and the DMRS correlation result of the PDSCH looks correct. I think it might be a synchronization issue, but I am not sure. 

Could you provide more information about your setup? What USRP or RU are you using for the srsDU and NR-Scope? Is the RU synchronized to any GPS signal and is the NR-Scope USRP connected to any GPSDO (external reference signal) or GPS antenna (internal GPS clock)? If they are using different synchronization source, could you try to make them the same (e.g. both synchronized to GPS like the commercial base stations) and try again?

The software synchronization function for 5G is not properly implemented in srsRAN so we decode the MIB/SSB once and rely on the external GPSDO for synchronization. We may try to improve the software synchronization in the future, but using a GPS synchronization is always a better option.

**Comment by olasierra** [comment]
Hi, thanks for the quick response. That was it! I have attached a GPSDO external source to both srsRAN and the Sniffer, and now I am getting almost all the DCIs associated with the user.

I will provide my configuration files for both srsRAN and NR-Scope for anyone interested.

### srsRAN gNB Config File (B210)
```
cu_cp:
  amf:
    addr: # Your address
    port:  # Your port
    bind_addr: # Your address
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=b200, num_recv_frames=64,num_send_frames=64 
  clock: gpsdo    # internal
  srate: 23.04
  otw_format: sc12
  tx_gain: 80
  rx_gain: 60

cell_cfg:     
  dl_arfcn: 627340      
  band: 78
  channel_bandwidth_MHz: 20
  nof_antennas_ul: 2
  nof_antennas_dl: 2
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
```
### NR Scope (X310)
```
nof_usrp_dev: 1
usrp_setting_0:
  ssb_freq: 3404640000      
  rf_args: "clock=gpsdo,type=x300,sampling_rate=23040000" ## For CBX daughterboard
  rx_gain: 75 # for x310 CBX, max rx gain is 31.5, for b210, it's around 80, for x310 TwinRX, max rx gain is 90
  min_rx_gain: 0
  max_rx_gain: 80
  srate_hz: 23040000       
  srsran_srate_hz: 23040000 
  nof_carriers: 1 # srsRAN rf setting, always set to be 1 for now. 
  nof_antennas: 1 # srsRAN rf setting, always set to be 1 for now.
  scs_index: 1 #(0: 15kHz, 1: 30kHz, ..., the u in standard)
  rf_log_level: "info"
  nof_rnti_worker_groups: 15 # number of of threads for DCI decoding, each will divide the UEs into small groups
  nof_bwps: 1 # number of BWP of the cell
  nof_workers: 15 # using worker pool to asynchronously process the slot data
  cpu_affinity: false # pin the worker's thread into CPU or not.

  log_name: "a.csv"
  google_dataset_id: "ngscope5g_dci_log_wanhr"
```

### Results obtained:

##### srsRAN Output:
[srsran_output.txt](https://github.com/user-attachments/files/18078567/srsran_output.txt)

##### NR-Scope Output
[nrscope_output.txt](https://github.com/user-attachments/files/18078549/nrscope_output.txt)

**Comment by WanHaoRan** [comment]
Thanks for the update, glad to see it works!
